import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import FormHeader from "~/components/Authentication/FormHeader";
import Layout from "~/components/Authentication/Layout";

const VerifyRequest: NextPage = () => (
  <>
    <Head>
      <title>Bestätigung Gesendet | Letzte Generation Österreich</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <div className="flex flex-col items-center justify-center gap-4">
        <FormHeader title="Bestätige deine E-Mail" />
        <p className="text-center text-white">
          Wir haben dir eine E-Mail geschickt. Bitte klicke auf den Link um dich
          anzumelden. Wenn du keine E-Mail erhalten hast, überprüfe bitte auch
          deinen Spam Ordner.
        </p>
        <Link href="/">Zurück zum Login</Link>
      </div>
    </Layout>
  </>
);

export default VerifyRequest;
