import Head from "next/head";
import _ from "lodash";
import Layout from "~/components/Dashboard/Layout";
import TitleCard from "~/components/Card/TitleCard";
import ProfileForm from "~/components/Profile/ProfileForm";
import { useSession } from "next-auth/react";

// const PHONE_REGEX = /^\+[1-9]\d{1,14}$/gim;

export default function Profile() {
  const { data: sessionData } = useSession();
  const id = sessionData?.user?.id;

  return (
    <>
      <Head>
        <title>Profil | Letzte Generation Österreich</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TitleCard title="Profil Einstellungen" topMargin="mt-2">
          {_.isNil(id) ? (
            <div className="flex flex-col items-center justify-center">
              <h1 className="text-2xl font-bold">No ID provided</h1>
            </div>
          ) : (
            <ProfileForm id={id} />
          )}
        </TitleCard>
      </Layout>
    </>
  );
}
