const MODAL_BODY_TYPES = Object.freeze({
  USER_DETAIL: "USER_DETAIL",
  NOTE_ADD_NEW: "NOTE_ADD_NEW",
  EVENT_ADD_NEW: "EVENT_ADD_NEW",
  EVENT_EDIT_EXISTING: "EVENT_EDIT_EXISTING",
  EVENT_VIEW_EXISTING: "EVENT_VIEW_EXISTING",
  EVENT_CONFIRM_DELETION: "EVENT_CONFIRM_DELETION",
  DEFAULT: "",
});

const RIGHT_DRAWER_TYPES = Object.freeze({
  NOTIFICATION: "NOTIFICATION",
});

export { MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES };
